server:
  port: 8082
spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-alias-package: com.springboot.mapper
  mapper-locations: classpath*:com/springboot/mapper/**/*.xml
logging:
  level:
    com.springboot.mapper: DEBUG #作为package(包)的前缀来设置日志级别
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true