server:
  port: 8082
spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-alias-package: com.springboot.mapper
  mapper-locations: classpath:mapping/*.xml